app:
    resource: "@AppBundle/Controller/"
    type:     annotation
video_show:
    path:      /video/{slug}
    defaults:  { _controller: AppBundle:Video:show }
login:
    path:      /login/
    defaults:  { _controller: AppBundle:Security:login }
home:
    path: /
    defaults: { _controller: AppBundle:Home:index }