app:
    resource: "@AppBundle/Controller/"
    type:     annotation
channel:
    path:      /channel/{slug}
    defaults:  { _controller: AppBundle:Channel:show }
upload:
    path:      /upload/{slug}
    defaults:  { _controller: AppBundle:Upload:show } 
profile:
    path:      /profile/{slug}
    defaults:  { _controller: AppBundle:Profile:show }    
login:
    path:      /login/
    defaults:  { _controller: AppBundle:Security:login }
home:
    path: /
    defaults: { _controller: AppBundle:Home:index }
gestion:
    path:     /gestion/
    defaults: { _controller: AppBundle:Gestion:index }
ajout_page:
    path:     /ajout_page/
    defaults: { _controller: AppBundle:AjoutPage:index }